### ISSUE TITLE
Implement a Code Formatter

### ISSUE THREAD

**Issue by manuelurenah** [clay/clay-starter#34]
## Is your feature request related to a problem? Please describe.

Right now, we rely on ESLint rules to stick to a code style convention for our development workflow. However, this does not enforce people to adopt those standards bringing noise when doing code review for a PR and introducing different code styles drifting from our standards.

## Describe the solution you'd like

A plausible solution would be to implement a pre-commit hook that would take care of this issue automatically before committing any changes to the repo. This would reduce the amount of noise brought by the different code styles from developers. Thus, making code review easier for everyone

## Describe alternatives you've considered

A good contender for this would be to implement [Prettier](https://prettier.io/) ✨ which would take care of it.

## Additional context

We would need to define a good set of rules to best fit our configuration

**Comment by james-owen** [comment]
Agreed. For the pre-commit hook we could try lint-staged, which only lints staged files and makes linting / prettifying snappier. Options for pre-commit hooks in Prettier docs [here](https://prettier.io/docs/en/precommit.html), suggesting use of lint-staged with husky. 

I don't think it will be a big problem, but we'll need to consider how we'll integrate [ESLint with Prettier](https://prettier.io/docs/en/eslint.html).

**Comment by james-owen** [comment]
We should consider using the `--require-pragma` option, to be able to select individual files to run Prettier on. This way we can get a couple of files on Prettier at a time. [Prettier Options](https://prettier.io/docs/en/options.html)

**Comment by manuelurenah** [comment]
I get your point, but I feel there's no need for the `--require-pragma` flag since we will only lint and format staged files with `lint-staged`. That being said, Prettier won't run for all files at once, just for the changed files and we can avoid having a big PR with code styles changes for all files.
