### ISSUE TITLE
Failing to run make

### ISSUE THREAD

**Issue by pedram80** [clay/clay-starter#38]
## Description

When trying to run make for the first time it seems to be failing on the index creation process

## Steps to Reproduce

execute make

Following error is noticed

ERROR [2019-04-10T20:41:09.526Z] (amphora-search/32596 on bobs-MacBook-Pro-4.local): Client.bulk errored on batch operation
    amphoraSearchVersion: "7.3.0"
    file: "/Users/bob/Desktop/Project_Workspaces/clay-starter/app/node_modules/amphora-search/lib/services/elastic.js"
    ops: [
      {
        "index": {
          "_index": "local_sites_v1",
          "_type": "_doc",
          "_id": "claydemo"
        }
      },
      {
        "name": "Clay Demo",
        "slug": "claydemo",
        "host": "localhost",
        "path": "",
        "port": 80,
        "protocol": "http",
        "assetDir": "public",
        "assetPath": "",
        "mediaPath": "localhost/media/sites/claydemo/",
        "siteIcon": "undefined"
      }
    ]
    items: [
      {
        "index": {
          "_index": "local_sites_v1",
          "_type": "_doc",
          "_id": "claydemo",
          "status": 403,
          "error": {
            "type": "cluster_block_exception",
            "reason": "blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
          }
        }
      }
    ]
    _label: "ERROR"
ERROR [2019-04-10T20:41:09.527Z] (amphora-search/32596 on bobs-MacBook-Pro-4.local): Error initialzing lists: Client.bulk errored on batch operation
    amphoraSearchVersion: "7.3.0"
    file: "/Users/bob/Desktop/Project_Workspaces/clay-starter/app/node_modules/amphora-search/lib/init.js"
    stack: "Error: Client.bulk errored on batch operation\n    at /Users/bob/Desktop/Project_Workspaces/clay-starter/app/node_modules/amphora-search/lib/services/elastic.js:384:17\n    at tryCatcher (/Users/bob/Desktop/Project_Workspaces/clay-starter/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/Users/bob/Desktop/Project_Workspaces/clay-starter/app/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/Users/bob/Desktop/Project_Workspaces/clay-starter/app/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/Users/bob/Desktop/Project_Workspaces/clay-starter/app/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/Users/bob/Desktop/Project_Workspaces/clay-starter/app/node_modules/bluebird/js/release/promise.js:694:18)\n    at _drainQueueStep (/Users/bob/Desktop/Project_Workspaces/clay-starter/app/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/Users/bob/Desktop/Project_Workspaces/clay-starter/app/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/Users/bob/Desktop/Project_Workspaces/clay-starter/app/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/Users/bob/Desktop/Project_Workspaces/clay-starter/app/node_modules/bluebird/js/release/async.js:17:14)\n    at processImmediate (internal/timers.js:443:21)"
    _label: "ERROR"

### Desktop

 - OS:  MacOS High Seirra
 - Node: v11.13.0
 - Docker version 18.09.2, build 6247962

**Comment by jonwinton** [comment]
@pedram80 it looks like the ElasticSearch docker container might be having issues. The  error `"reason": "blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"` is saying your index is set into a read only state which is usually caused by hard disk limitations.

See: https://stackoverflow.com/questions/48155774/elasticsearch-read-only-allow-delete-auto-setting and https://www.elastic.co/guide/en/elasticsearch/reference/6.7/disk-allocator.html

I would recommend the following:

1) Stop all docker containers
2) Run `make clear-data` to wipe your local instance's data
3) Ensure docker has enough allocated hard disk/memory on your machine
4) Run through the startup process

Let me know if that doesn't work!

**Comment by pedram80** [comment]
Yes that did the trick , i added following line to elastic search.yml
cluster.routing.allocation.disk.threshold_enabled : false

**Comment by jonwinton** [comment]
👍 perfect, glad that worked out!
