### ISSUE TITLE
Makefile has inconsistent keys

### ISSUE THREAD

**Issue by jonathan-graf** [clay/clay-starter#4]
`make bootstrap` is hard-coded to use the `claydemo-local` key.  

`make bootstrap-user` is hardcoded to use the `starter` key.

`make add-access-key` is hardcoded to use the `starter` key.

This should be consistent.

**Comment by jonwinton** [comment]
Ah, sorry about that @jonathan-graf! I fixed that late yesterday and we should be good now.
