### ISSUE TITLE
Remove GOOGLE_CONSUMER_KEY from .env

### ISSUE THREAD

**Issue by manuelurenah** [clay/clay-starter#41]
## Description

It has being pointed out that there is a Google consumer key inside the `.env` file that shouldn't be tracked by the version control.

## Steps to Reproduce

1. Go to this file: https://github.com/clay/clay-starter/blob/master/app/.env
2. Check which keys should excluded

## Expected Behavior

The `.env` file should be untracked and we can set a `.env.sample` file with sample key/values to maintain the standard

## Screenshots

- `N/A`

## Additional Context

- `N/A`

**Comment by PedroAlbR** [comment]
This might come in handy: [Removing sensitive data from a repository](https://help.github.com/en/articles/removing-sensitive-data-from-a-repository)

**Comment by TTaitFoster** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BUG] Secret key posted in clay-starter repo](https://trello.com/c/0rIzIigk/227-bug-secret-key-posted-in-clay-starter-repo)

**Comment by PedroAlbR** [comment]
Closed because of #42
